### PR TITLE
fix(ts/analyzer): handle static index signatures of a class

### LINKED ISSUE #351: Handle static index signatures of a class
https://github.com/dudykr/stc/blob/dfa3b9f9916f7411890cf04b26496a60c4ab0eb4/crates/stc_ts_type_checker/tests/conformance/classes/staticIndexSignature/staticIndexSignature1.ts#L1-L11

Should success

### PR DESCRIPTION
**Pull request by iheyunfei**
**Description:**

It's indeed a lot of fun writing stc. :)

**BREAKING CHANGE:**

**Related issue (if exists):**
Fix #351

### CODE REVIEW

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs [hunk 1]
```diff
@@ -2503,10 +2509,49 @@ impl Analyzer<'_, '_> {
...
+                                    index_signature_fallback = Some(Ok(index
+                                        .type_ann
+                                        .clone()
+                                        .map(|v| *v)
+                                        .unwrap_or_else(|| Type::any(span, Default::default()))));
+                                    continue;
+                                }
+
+                                let indexed = self.assign(span, &mut Default::default(), index_ty, &prop_ty).is_ok();
+                                println!("{:#?}: {:#?} {:#?} ", prop, index_ty, prop_ty);
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:2536]: Can you remove this?

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs [hunk 2]
```diff
@@ -2503,10 +2509,49 @@ impl Analyzer<'_, '_> {
...
+                                println!("index.type_ann: {:#?}", index.type_ann);
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:2537]: Ditto

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thank you!

**Review by kdy1 — APPROVED** [review]
Thank you!
