### PR TITLE
fix(ts/analyzer): fix error code for exports with primitive names

### LINKED ISSUE #399: Change the error code of no-such-variable for exports with special names
https://github.com/dudykr/stc/blob/4139483e8a19adc3ba52c0637a7676c6d9ecbdb2/crates/stc_ts_type_checker/tests/conformance/externalModules/exportNonLocalDeclarations.ts#L1-L2

This should fail with two `TS2661`, but it currently fails with

```
============================================================
TS2304

  x context: tried to reexport with named export specifier (at crates/stc_ts_file_analyzer/src/analyzer/export.rs:321:23)
  | NoSuchVar {
  |     span: Span {
  |         lo: BytePos(
  |             12,
  |         ),
  |         hi: BytePos(
  |             18,
  |         ),
  |         ctxt: #0,
  |     },
  |     name: string#1,
  | }
   ,-[$DIR/tests/conformance/externalModules/exportNonLocalDeclarations.ts:1:1]
 1 | export { string };
   :          ^^^^^^
   `----
TS2304

  x context: tried to reexport with named export specifier (at crates/stc_ts_file_analyzer/src/analyzer/export.rs:321:23)
  | NoSuchVar {
  |     span: Span {
  |         lo: BytePos(
  |             36,
  |         ),
  |         hi: BytePos(
  |             42,
  |         ),
  |         ctxt: #0,
  |     },
  |     name: number#1,
  | }
   ,-[$DIR/tests/conformance/externalModules/exportNonLocalDeclarations.ts:2:1]
 2 | export type { number };
   :               ^^^^^^
   `----

============================================================
2 unmatched errors out of 2 errors. Got 2 extra errors.
Wanted: [RefError { line: 1, column: 10, code: "TS2661" }, RefError { line: 2, column: 15, code: "TS2661" }]
Unwanted: [(1, "TS2304"), (2, "TS2304")]
```

We should change the error code if the name is a typescript keyword.

### PR DESCRIPTION
**Pull request by togami2864**
**Related issue (if exists):**
fix #399

### CODE REVIEW

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs [hunk 1]
```diff
@@ -3542,11 +3542,16 @@ impl Analyzer<'_, '_> {
                     }
                     .into())
                 } else {
-                    Err(ErrorKind::NoSuchVar {
-                        span,
-                        name: i.clone().into(),
+                    match &*i.sym {
+                        "any" | "never" | "unknown" | "string" | "number" | "bigint" | "boolean" | "undefined" | "symbol" => {
+                            Err(ErrorKind::CannotExportNonLocalVar { span }.into())
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:3547]: We should not do this here

Comment (kdy1) [reply crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:3547]: We should do this check from https://github.com/dudykr/stc/blob/bc089c22e747a4798f9ea80fba9ac5a011b10677/crates/stc_ts_file_analyzer/src/analyzer/export.rs#L322-L329 instead

**Review by kdy1 — CHANGES_REQUESTED** [review]

**Review by kdy1 — APPROVED** [review]
Thank you!
