### PR TITLE
fix: fix ts2323

### LINKED ISSUE #664: The error for multiple exported function declarations should be preferred over error for multiple default
https://github.com/dudykr/stc/blob/94a2b2090d154669348b75f1a40d0899fd90c8a4/crates/stc_ts_type_checker/tests/conformance/es6/modules/multipleDefaultExports04.ts#L4-L8

should fail with two [`TS2323`](https://github.com/microsoft/TypeScript/blob/aa658257c9faa2568602bf8d59b9dc1fb19870c7/src/compiler/diagnosticMessages.json#L1747-L1750) but `stc` currently emits two `TS2528`.

```

============================================================
TS2528

  x DuplicateDefaultExport {
  |     span: Span {
  |         lo: BytePos(
  |             54,
  |         ),
  |         hi: BytePos(
  |             70,
  |         ),
  |         ctxt: #0,
  |     },
  | }
   ,-[$DIR/tests/conformance/es6/modules/multipleDefaultExports04.ts:3:1]
 3 |
 4 | ,-> export default function f() {
 5 | `-> }
   `----
TS2528

  x DuplicateDefaultExport {
  |     span: Span {
  |         lo: BytePos(
  |             87,
  |         ),
  |         hi: BytePos(
  |             103,
  |         ),
  |         ctxt: #0,
  |     },
  | }
   ,-[$DIR/tests/conformance/es6/modules/multipleDefaultExports04.ts:6:1]
 6 |
 7 | ,-> export default function f() {
 8 | `-> }
   `----

============================================================
2 unmatched errors out of 4 errors. Got 2 extra errors.
Wanted: [RefError { line: 4, column: 25, code: "TS2323" }, RefError { line: 7, column: 25, code: "TS2323" }]
Unwanted: [(4, "TS2528"), (7, "TS2528")]
```

### PR DESCRIPTION
**Pull request by blacktoast**
**Description:**

When function is export default, it seems that it should return TS2323 regardless of whether the function name is the same or different, so I fixed it.

**BREAKING CHANGE:**

**Related issue (if exists):**
fix #664

### CODE REVIEW

File: crates/stc_ts_file_analyzer/src/analyzer/export.rs [hunk 1]
```diff
@@ -175,13 +175,25 @@ impl Analyzer<'_, '_> {
         let _tracing = dev_span!("report_errors_for_duplicated_exports_of_var");
 
         let v = self.data.for_module.exports_spans.entry((sym.clone(), IdCtx::Var)).or_default();
+        let func_spans = &self.data.fn_impl_spans;
+        let mut is_duplicated_func = false;
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/export.rs:179]:
```rust
let is_duplicated_func = func_spans.iter().any(|(_, spans)| spans.len() >= 2);
```

will work

File: crates/stc_ts_file_analyzer/src/analyzer/export.rs [hunk 2]
```diff
@@ -175,13 +175,25 @@ impl Analyzer<'_, '_> {
...
+
+        for (_, func_span_vec) in func_spans.iter() {
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/export.rs:181]: And this loop can be removed

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thank you!
Can you rebase or merge, too?

File: crates/stc_ts_file_analyzer/src/analyzer/export.rs (hunk 2 above)
Comment (blacktoast) [reply crates/stc_ts_file_analyzer/src/analyzer/export.rs:181]: Thanks I will change

**Comment by blacktoast** [comment]
I rebased code and reflected the code review

**Review by kdy1 — APPROVED** [review]
Thank you!
