### PR TITLE
fix(ts/checker): Default value of an object pattern property should not change type if it's assignable

### LINKED ISSUE #189: Default value of an object pattern property should not change type if it's assignable
https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_type_checker/tests/conformance/types/nonPrimitive/nonPrimitiveAndEmptyObject.ts#L6-L17

This should success.

image

`access_property` of `((BarProps#1 & object) | {})` is expected to fail, because `{}` does not have the property.
But the type of `fooProps` should be `(BarProps#1 & object)` (without union)

I think the logic at https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs#L483-L500 is problematic, and I think we should adjust it to ignore default value if the type of the default value is assignable to the original type.

### PR DESCRIPTION
**Pull request by kharvd**
**Description:**

**Related issue (if exists):**
Fix #189

### CODE REVIEW

File: crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs [hunk 1]
```diff
@@ -120,7 +120,17 @@ impl Analyzer<'_, '_> {
                     }
                 }
 
-                let mut ty = opt_union(span, ty, default);
+                let mut ty = match (default, ty) {
+                    (Some(default), Some(ty)) => {
+                        if self.extends(span, &default, &ty, Default::default()).is_some() {
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs:125]: I think `extends().is_some()` is wrong because `extends()` returns `None` only if it cannot be determined. i.e., type parameter

Comment (kdy1) [reply crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs:125]: I think it should be `if let Some(true) = self.extends(...) {} else {}`

**Review by kdy1 — CHANGES_REQUESTED** [review]
Also, can you sign the CLA?

File: crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs (hunk 1 above)
Comment (kharvd) [reply crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs]: Oops, gotcha, fixed!

**Review by kdy1 — APPROVED** [review]
Thanks!
