### PR TITLE
fix(ts/analyzer): Fix wrong error code when assigning to non-variable

### LINKED ISSUE #179: Change error code for using `module` as LHS
https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_type_checker/tests/conformance/expressions/valuesAndReferences/assignments.ts#L10-L11

This line should fail with `TS2708`, but it fails with `TS2539`.

image

The problematic code is at

https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs#L401-L417

and we should use `Errorr::convert_err` to adjust the error variant.

### PR DESCRIPTION
**Pull request by hyp3rflow**
**Description:** Fix #179 

**BREAKING CHANGE:**

**Related issue (if exists):** #179

### CODE REVIEW

**Comment by hyp3rflow** [comment]
I succeeded in passing the `assignments.ts` conformance TC, but it seems that this change occurs additional error on another TCs. I'll check this further.

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs [hunk 1]
```diff
@@ -405,14 +405,24 @@ impl Analyzer<'_, '_> {
...
-                                }
-                                _ => {}
+                        .convert_err(|err| {
+                            skip_right = true;
+                            match err.actual() {
+                                Error::CannotAssignToNonVariable { .. } => match analyzer.scope.vars.get(&i.into()) {
+                                    Some(v) if v.kind == VarKind::Fn => Error::CannotAssignToFunction { span },
+                                    _ => err,
+                                },
+                                Error::NotVariable { .. } => match analyzer.type_of_raw_var(i, TypeOfMode::LValue) {
```
Comment (littledivy) [inline crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:415]: This is not good for performance. The extra `type_of_var` call is wasting a lot of cycles here. I think `Error::NotVariable` should be modified to contain `ty` it got.

Comment (hyp3rflow) [reply crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs]: Thanks! I fixed this as you said, but I'm not sure I did it right. Could you review my fix? [`8507c7b` (#192)](https://github.com/dudykr/stc/pull/192/commits/8507c7b3075a853907dceaf800e09fc90a0fddb7)

Comment (littledivy) [reply crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs]: LGTM! cc @kdy1

File: crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs [hunk 2]
```diff
@@ -875,6 +875,7 @@ impl Analyzer<'_, '_> {
                                     return Err(Error::NotVariable {
                                         span: i.id.span,
                                         left: lhs.span(),
+                                        ty: Some(box ty.normalize().clone()),
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: Please change this to `ty.clone()`

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs [hunk 3]
```diff
@@ -405,14 +405,27 @@ impl Analyzer<'_, '_> {
...
-                                    skip_right = true;
+                        .convert_err(|err| {
+                            skip_right = true;
+                            match err.actual() {
+                                Error::CannotAssignToNonVariable { .. } => match analyzer.scope.vars.get(&i.into()) {
+                                    Some(v) if v.kind == VarKind::Fn => Error::CannotAssignToFunction { span },
+                                    _ => err,
+                                },
+                                Error::NotVariable { ty, .. } => match ty {
+                                    Some(ty) => match **ty {
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:416]: Please change this to `match ty.normalize() { ... }`

Comment (kdy1) [reply crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:416]: In this way we can avoid cloning

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thank you so much!
Other changes look good to me

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs [hunk 4]
```diff
@@ -2891,7 +2904,11 @@ impl Analyzer<'_, '_> {
         let mut modules = vec![];
         let mut ty = self.type_of_raw_var(i, type_mode)?;
         if type_mode == TypeOfMode::LValue && (ty.is_class_def() || ty.is_enum_type()) {
-            return Err(Error::NotVariable { span, left: span });
+            return Err(Error::NotVariable {
+                span,
+                left: span,
+                ty: Some(box ty.normalize().clone()),
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:2910]: Oh same here

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs [hunk 5]
```diff
@@ -2924,7 +2941,13 @@ impl Analyzer<'_, '_> {
             if let Some(types) = self.find_type(self.ctx.module_id, &id)? {
                 for ty in types {
                     match ty.normalize() {
-                        Type::Module(..) => return Err(Error::NotVariable { span, left: span }),
+                        Type::Module(..) => {
+                            return Err(Error::NotVariable {
+                                span,
+                                left: span,
+                                ty: Some(box ty.normalize().clone()),
```
Comment (kdy1) [inline crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:2948]: Ditto

**Review by kdy1 — CHANGES_REQUESTED** [review]

File: crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs (hunk 2 above)
Comment (hyp3rflow) [reply crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: Well, how do I have to type `Error::NotVariable`?
Currently the `ty` is Option<Box<Type>>, it makes conflict with this changes.

Comment (hyp3rflow) [reply crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: fyi. ty is `Cow<Type>` in this file.

Comment (kdy1) [reply crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: Ah, I meant removing `normalize()` only

Comment (kdy1) [reply crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: Actually we use `Type::Arc` to avoid cloning and `normalize` dereferences `Type::Arc` into actual data type. So we should not call `.normalize().clone()` because it will clone actual data instead of `Arc`

Comment (kdy1) [reply crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: Oh.. `Cow` is problematic at the moment, I'll optimize this in future.  Thank you!
Anyway, please change match to call `normalize()` as it will guarantee that it'll work in future

Comment (hyp3rflow) [reply crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: Thanks! `normalize()` at the use-side, right? I'll change it. @kdy1

Comment (kdy1) [reply crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:878]: Yup

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs (hunk 5 above)
Comment (hyp3rflow) [reply crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:2948]: ty is `Cow<Type>` in here, too!

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs (hunk 4 above)
Comment (hyp3rflow) [reply crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs]: ✅ [`43a0b63` (#192)](https://github.com/dudykr/stc/pull/192/commits/43a0b63877b6837b2505f8695264226b0c134fdc)

File: crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs (hunk 3 above)
Comment (hyp3rflow) [reply crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs]: ✅ [`43a0b63` (#192)](https://github.com/dudykr/stc/pull/192/commits/43a0b63877b6837b2505f8695264226b0c134fdc)

**Review by kdy1 — APPROVED** [review]
Thanks!
